
- name: criando os usuarios padroes
  user:
   name: "{{item.nome}}"
   shell: "{{item.bash}}"
   password: "{{item.senha}}"
   home: "{{item.home}}"
  with_items:
   - { nome: douglas, bash: /bin/bash, senha: '$1$deubcTlc$oUwXX52b4y1hjUPbdAwO51', home: /srv/douglas }
   - { nome: developer, bash: /bin/bash, senha: '$1$deubcTlc$oUwXX52b4y1hjUPbdAwO51', home: /srv/developer }
   - { nome: devops, bash: /bin/bash, senha: '$1$deubcTlc$oUwXX52b4y1hjUPbdAwO51', home: /srv/devops }
