---
- name: instalando pacote conforme OS
  hosts: all
  tasks:
   - name: Instalando pacotes genericos
     package:
      name:
       - vim
       - htop
       - cowsay
       - figlet
      state: present
    
   - name: instalando pacotes somente no debian
     package:
      name:
       - apache2
     when: ansible_os_family == "Debian"

   - name: instalando pacotes somente no redhat
     package:
      name:
       - httpd
       - epel-release
     when: ansible_os_family == "RedHat"

