---
- name: utilizando variavel na playbook
  hosts: "{{maquina}}"
  vars: 
   - maquina: default
   - pacotes: default 
  tasks:
   - name: verificando pacote do vim
     package:
      name: "{{pacotes}}"
      state: present
   
