---
- name: configurando um servidor web
  hosts: "{{maquinas}}"
  vars:
   - maquinas: default
  tasks:
   - name: garantindo o apache instalado
     package:
      name: apache2
     when: ansible_os_family == "Debian"

   - name: garantindo o apache instalado em RedHat
     package:
      name: httpd
     when: ansible_os_family == "RedHat"

   - name: criando minha pag web
     template:
      src: index
      dest: /var/www/html/index.html
