---
- name: adicionando pacotes
  hosts: all
  tasks:
#   - name: instalando vim
#     package:
#      name: vim
#      state: present

   - name: enviando um arquivo
     copy:
      src: /etc/hosts
      dest: /etc/hosts
   - name: garantindo uma nova linha no etchosts
     lineinfile:
      path: /etc/hosts
      line: '192.168.200.1 desktop'

   - name: garantindo um bloco de configuracao
     blockinfile:
      path: /etc/hosts
      block: |
       192.168.0.10 desktop1
       192.168.0.11 desktop2
