---
- name: utilizando variavel na playbook
  hosts: "{{maquina}}"
  vars: 
   - maquina: default 
   - usario: usuario
  tasks:
   - name: verificando usuario
     user:
      name: "{{usuario}}"
      state: present

